### ISSUE TITLE
Option to set user

### ISSUE THREAD

**Issue by alippai** [VladimirRybalko/angular-applicationinsights#25]
An option to update the userid and accountid during the app run would be nice.
After somebody logs in, I'd like to set the ids, so the tracking later matches his session and group.

**Comment by gligoran** [comment]
+1

**Comment by tedvanderveen** [comment]
+1

**Comment by izefler** [comment]
Someone could set this? What would be the alternative?

**Comment by amigup** [comment]
+1

**Comment by wk001** [comment]
👍

**Comment by patrickpenn** [comment]
+1

**Comment by rosieks** [comment]
+1
