### ISSUE TITLE
No browser page load data

### ISSUE THREAD

**Issue by megachan** [VladimirRybalko/angular-applicationinsights#26]
I found that there was no browser page load data when I used angular-applicationinsights. However, data from activity by page name was shown perfectly. Are there any ways to show browser page load using angular-applicationinsights?

Kind regards,
Yui

**Comment by khaines** [comment]
Currently not at the moment. Page load times are something planned for being added however.

**Comment by frederikd** [comment]
@khaines great to hear that you are planning this for the future, and thanks for the plugin in general.
Do you have any idea when roughly you are planning to work on this? Or do you have some pointers as to what the issue is with page load times so we could look into adding this ourselves in the meantime? Thanks!

**Comment by khaines** [comment]
Hopefully soon, as my time frees up. I'm always open to contributions if someone wants to add a missing feature before I can get to it. Really the pointer about why page load times aren't tracked in this module is that there is no code doing that job. Angular has some events that are fired when the view is transitioned (both start and finish) and one of those events is used to track the view data. These could probably be a good basis for load time tracking.

**Comment by frederikd** [comment]
Okay, thanks. We might struggle but we'll try to have a look at it ourselves and see how we go. Will send it through if we get anywhere, but can't promise anything. :)

**Comment by bfelda** [comment]
I see that the source has a duration parameter but it's missing in dist.  Still a work in progress?

**Comment by VladimirRybalko** [comment]
@bfelda Yes, work is still in progress. Unfortunately project was not supported for a long time. But now we changed the owner. So I hope that work will be continued. If you'd like to be a contributor, it will be cool.

**Comment by VladimirRybalko** [comment]
@bfelda I've added the 'duration' parameter in dist. Welcome to use it.

**Comment by VladimirRybalko** [comment]
Seems it has some bugs with duration parameter for UI router navigation. Need to check it more carefuly.

**Comment by VladimirRybalko** [comment]
I've fixed all evil bugs with UI router. The task is done.
