### ISSUE TITLE
Vital Info not getting logged

### ISSUE THREAD

**Issue by rahulseth01** [VladimirRybalko/angular-applicationinsights#34]
We are having AppInsight enabled in our UWP Win 10 App.

We then noticed that some of the vital fields are not getting captured at all:
• ContextApplicationVersion (e.g 3.4.0.0)
• ContextDeviceOemName (e.g Hewlett-Packard, Dell Inc.)
• ContextDeviceDeviceModel (e.g HP Z230 SFF Workstation, XPS 12 9Q23)

For initializing the AI component, we are using below code:

```
           applicationInsightsServiceProvider.configure('g_appInstrumentationKey');
```

**Comment by khaines** [comment]
There is no auto detection of these values in this module as this is primarily a browser module. A future  version should probably allow an app developer to set these directly.

**Comment by VladimirRybalko** [comment]
I agree that the best solution will be implementation of custom context properties. App developer will set these directly.

**Comment by VladimirRybalko** [comment]
Hi @rahulseth01
@tutujohngeorge has already added ability to added custom properties into appinsight module.
I suppose it would resolve your issue too.
