### ISSUE TITLE
Support UI Router page views

### ISSUE THREAD

**Issue by masimplo** [VladimirRybalko/angular-applicationinsights#39]
I noticed that you only register on locationChangeSuccess events which is fine for anyone using the default router. But since UIRouter is the most popular router used in angular1 apps I think that supporting it out of the box would be nice. 
Handling is identical with one you have now, but you should also listen to $stateChangeSuccess event. Having both event listeners registered should cause any trouble I believe.

**Comment by patrickpenn** [comment]
+1

**Comment by VladimirRybalko** [comment]
Now, **$viewContentLoaded** event is supporting out from the box. It allows to catch as **$locationChangeSuccess**  as **$stateChangeSuccess** event.

**Comment by VladimirRybalko** [comment]
Duration parameter works incorrectly for UIRoute mechanism. So I need to redesign it.

**Comment by VladimirRybalko** [comment]
I've completed the last fixes with duration parameter for UI Router. (look at #26 ).
Now app could track page view events for both mechanism: ngRoute and ui-route.
App trackes _ngRoute_ events by default ($locationChangeStart and $locationChangeSuccess). 
If you need to track ui-route events ($stateChangeStart and $stateChangeSuccess) you will turn on the **autoStateChangeTracking** option too.
