### ISSUE TITLE
error calling: https://dc.services.visualstudio.com/v2/track

### ISSUE THREAD

**Issue by lucasowens** [VladimirRybalko/angular-applicationinsights#44]
When I first run my application locally I get the following error:

Failed to load resource: the server responded with a status of 400 (109: Field 'name' on type 'EventData' is required but missing or empty. Expected: string, Actual:)

All subsequent calls seem to go through fine. Any idea what I could be doing wrong?

**Comment by VladimirRybalko** [comment]
Seems that issue was resolved early. An update of the nuget package fixed this problem.
