### ISSUE TITLE
Data not showing up in appinsights

### ISSUE THREAD

**Issue by jrmcdona** [VladimirRybalko/angular-applicationinsights#50]
Hello0
I am writing an event to App Insights, however, it is not making it to the App insights portal.

Not seeing any errors either.  I see the angular-appinsights module is writing out the object to the browser console and I see my instrumentation key is present.

Anything that would help me debug this?

Thanks

**Comment by jrmcdona** [comment]
Is it possible that this will not work if the SDK is installed and ASP.NET has the app insights configured?  Seems like that wouldn't matter here within the angular app, but something is going wrong here.   I am not getting any traces to the App insights service in fiddler either for my events.  Thanks

**Comment by justinhomes** [comment]
i have the same problem, i do not see any calls made to azure

**Comment by justinhomes** [comment]
@jrmcdona  did you find solution to ur issue?

**Comment by jrmcdona** [comment]
@justinhomes never did and never went back to trying to figure it out

**Comment by VladimirRybalko** [comment]
Hi, @justinhomes and @jrmcdona .
Seems that you faces with the "developer mode" option.
Unfortunatelly there were some discrepancy between documentation and source code.
I'm sorry for misunderstanding. Now everything is fixed.
Moreover I'm going to do "developer mode" is inactive by default. Look at the #19 

So now you can configure appInsights as
```Javascript
<script language="javascript">
    var amazingApp = angular.module('amazingApp', ['ApplicationInsightsModule']);

    amazingApp.config(function(applicationInsightsServiceProvider){
        var options = {applicationName:'amazingApp', developerMode: false};
        // Configuration options are described below     
        applicationInsightsServiceProvider.configure('<PUT YOUR APPLICATION INSIGHTS KEY HERE', options );
    });
 </script>
```
