### ISSUE TITLE
Missing line & column numbers

### ISSUE THREAD

**Issue by Compulsed** [VladimirRybalko/angular-applicationinsights#52]
This current version of Application insights does not correctly set the line and column numbers in the AI portal.

This is not a problem with the current version of the JavaScript API

![image](https://cloud.githubusercontent.com/assets/1109278/20947475/6f20262e-bc63-11e6-951f-2e154169fc77.png)

Awesome project, and if possible would love to see a fix!

**Comment by VladimirRybalko** [comment]
Thanks for reporting this issue. It will be great if you'd like to contribute a fix!
Nice to hear your words about project. You always could click the star button to support us.
