### ISSUE TITLE
Adding custom tags to tracking

### ISSUE THREAD

**Issue by tutujohngeorge** [VladimirRybalko/angular-applicationinsights#54]
I have a requirement to add custom tags to the events getting logged from my angular application like shown below. Is it possible currently? 

![capture](https://cloud.githubusercontent.com/assets/20303714/21548584/2848b61c-cdbb-11e6-8c74-348fa7baab68.JPG)

**Comment by VladimirRybalko** [comment]
Hi @tutujohngeorge. Thanks to your feedback.
But unfortunately it's not possible yet. I'm going to add the custom tags in the #34 issue. However if you decided to develop it yourself it would be great. I always glad the new pull requests from community.
