### ISSUE TITLE
Adding custom error identifier to exception tracking

### ISSUE THREAD

**Issue by tutujohngeorge** [VladimirRybalko/angular-applicationinsights#55]
We have a SPA application with Web API backend which uses application insights. For any error encountered, we generate a unique ID to show to the user, so that we can correlate it back in the App Insights. I am able to do the same in Web API; but is there a way to use the same in SPA using this plugin?

![capture](https://cloud.githubusercontent.com/assets/20303714/21552120/68a5f8b6-cdcd-11e6-9389-5431c5ebec2f.JPG)

**Comment by VladimirRybalko** [comment]
@tutujohngeorge 
Unfortunately not yet.
App uses the internal UUID factory to generate any unique identifiers. 
But your idea seems interesting.
