### ISSUE TITLE
Add latest version to bower

### ISSUE THREAD

**Issue by rosieks** [VladimirRybalko/angular-applicationinsights#61]
The latest version in bower is 0.2.8 - could you add the latest (0.3.1)?

**Comment by VladimirRybalko** [comment]
Hi @khaines
Hope I find you well.
Seems that I faced with one issue. Unfortunately, I can't resolve it myself.
I need to update bower package. However bower package relates with your repository, so I don't have any abilities for pushing new changes to bower.
Could you please pull all my changes to update package.
Thanks in advance.

P.S. I've duplicated my message here.

**Comment by VladimirRybalko** [comment]
Hi @rosieks 
I suggest to wait some time. If I do not get feedback from @khaines I will register a new bower package.

**Comment by rosieks** [comment]
Thanks @VladimirRybalko,
Then I will wait

**Comment by khaines** [comment]
I will try to take care of this tonight as well as get that bower package
changed to look at the right location :)

Cheers,

ken

**Comment by VladimirRybalko** [comment]
@khaines any news about this issue?

**Comment by khaines** [comment]
There isn't a way to transfer it unfortunately, so I had to deregister the package. Please feel free to register it again

**Comment by khaines** [comment]
Correction it did get registered to the new location :), so folks can once again get the latest updates via bower

![image](https://user-images.githubusercontent.com/1144092/30391298-b1aca620-986d-11e7-9539-25a60ab73563.png)

**Comment by VladimirRybalko** [comment]
@khaines it's great! Thanks you.
So bower package is still accessible via the old name: "_bower install angular-applicationinsights_", isn't it?

**Comment by khaines** [comment]
yes it is...same name

On Thu, Sep 14, 2017 at 12:28 AM, Vladimir Rybalko <notifications@github.com
