### ISSUE TITLE
Why custom header are used in ApplicationInsightsInterceptor

### ISSUE THREAD

**Issue by n0is** [VladimirRybalko/angular-applicationinsights#66]
Hey @VladimirRybalko ,

Since I'm using your module in our app, I've noticed that our sever received a lot more of OPTION requests.  I didn't know exactly where it could come from until I read in some documentation that custom headers could trigger such requests.  I remember that I add to add 'x-ms-request-root-id', 'x-ms-request-id' in our web.config file since they're used in this lib which make me think that these headers could be the reason why we get more OPTION requests now.

I suppose these headers are useful and I don't know why.  Can you explain me why they're used and a piece of documentation?

Thanks!

Quentin.

**Comment by VladimirRybalko** [comment]
Hey, @n0is 
The both headers are correlation headers that are used by Microsoft to link different telemetry requests.
You can find more information [here](https://docs.microsoft.com/en-us/azure/application-insights/application-insights-correlation)
